# Generated by Django 3.0.1 on 2020-03-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
