# Generated by Django 2.2 on 2020-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_text_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='source',
        ),
        migrations.AddField(
            model_name='text',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
