# Generated by Django 2.2 on 2020-03-26 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200326_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
