# Generated by Django 2.2.4 on 2020-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_text_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
    ]
