# Generated by Django 2.2 on 2020-04-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200402_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Tag'),
        ),
    ]
