# Generated by Django 2.2 on 2020-04-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20200402_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='tag',
        ),
    ]
