# Generated by Django 2.2 on 2020-04-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_text_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='subject',
        ),
    ]
