# Generated by Django 3.0.7 on 2020-07-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Type'),
        ),
    ]
