# Generated by Django 3.0.7 on 2020-07-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_text_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='text',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
        migrations.AddField(
            model_name='text',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
    ]
